const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  minimize: () => ipcRenderer.send('win:minimize'),
  toggleMaximize: () => ipcRenderer.send('win:toggle-maximize'),
  close: () => ipcRenderer.send('win:close'),
  isMaximized: () => ipcRenderer.invoke('win:is-maximized'),
  onMaximized: (cb) => ipcRenderer.on('window:maximized', (_e, val) => cb(val)),
  browserDetectStart: () => ipcRenderer.send('browser:detect-start'),
  onBrowserTitles: (cb) => ipcRenderer.on('browser:titles', (_e, list) => cb(list)),
  openExternal: (url) => ipcRenderer.invoke('external:open', String(url)),
  focus: () => ipcRenderer.invoke('win:focus'),
  pickFolder: () => ipcRenderer.invoke('fs:pick-folder'),
  listFolder: (dir) => ipcRenderer.invoke('fs:list-files', String(dir)),
  renameFile: (dir, from, to) => ipcRenderer.invoke('fs:rename-file', String(dir), String(from), String(to)),
  copyText: (txt) => ipcRenderer.invoke('clipboard:set-text', String(txt)),
  savePng: (dataUrl, name) => ipcRenderer.invoke('fs:save-png', String(dataUrl), String(name)),
  watchOrganizer: (p) => ipcRenderer.invoke('organizer:watch', p),
  onOrganizerNew: (cb) => ipcRenderer.on('organizer:new', (_e, names) => cb(names)),
  saveState: (data) => ipcRenderer.invoke('state:save', String(data)),
  loadState: () => ipcRenderer.invoke('state:load'),
  stateInfo: () => ipcRenderer.invoke('state:info'),
  stateWipe: () => ipcRenderer.invoke('state:wipe'),
  discordConnect: (p) => ipcRenderer.invoke('discord:connect', p),
  setPresence: (p) => ipcRenderer.invoke('discord:set', p),
  clearPresence: () => ipcRenderer.invoke('discord:stop'),
  onDiscordStatus: (cb) => ipcRenderer.on('discord:status', (_e, s) => cb(s)),
  onUpdateStatus: (cb) => ipcRenderer.on('update:status', (_e, s) => cb(s)),
  saveSecret: (key, value) => ipcRenderer.invoke('secret:save', key, value),
  loadSecret: (key) => ipcRenderer.invoke('secret:load', key),
  updateCheckNow: () => ipcRenderer.invoke('update:check-now'),
  scrobbleNativeStart: () => ipcRenderer.invoke('scrobble:native-start'),
  scrobbleNativeStop: () => ipcRenderer.invoke('scrobble:native-stop'),
  onScrobbleNative: (cb) => ipcRenderer.on('scrobble:native', (_e, evt) => cb(evt)),
  gameGetStats: () => ipcRenderer.invoke('game:get-stats'),
  gameSaveStats: (stats) => ipcRenderer.invoke('game:save-stats', stats),
  gameListTrophies: () => ipcRenderer.invoke('game:list-trophies'),
  gameAddTrophy: (t) => ipcRenderer.invoke('game:add-trophy', t),
  gameAddHistory: (entry) => ipcRenderer.invoke('game:add-history', entry),
  gameHistory: (limit) => ipcRenderer.invoke('game:history', limit),
  gameRecordEpisode: (evt) => ipcRenderer.invoke('game:record-episode', evt),
  gameScrobbleHistory: (limit) => ipcRenderer.invoke('game:scrobble-history', limit),
  gameCoinSummary: () => ipcRenderer.invoke('game:coin-summary'),
  gameScrobbleStats: () => ipcRenderer.invoke('game:scrobble-stats'),
  storeList: () => ipcRenderer.invoke('store:list'),
  storeUpsert: (items) => ipcRenderer.invoke('store:upsert', items),
  storePurchase: (itemId, rank) => ipcRenderer.invoke('store:purchase', itemId, rank),
  storeEquip: (itemId, on) => ipcRenderer.invoke('store:equip', itemId, on),
  storeInventory: () => ipcRenderer.invoke('store:inventory'),
  seasonGet: (id) => ipcRenderer.invoke('season:get', id),
  seasonSave: (s) => ipcRenderer.invoke('season:save', s),
  seasonGrantItem: (item) => ipcRenderer.invoke('season:grant-item', item)
});