const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  minimize: () => ipcRenderer.send('win:minimize'),
  toggleMaximize: () => ipcRenderer.send('win:toggle-maximize'),
  close: () => ipcRenderer.send('win:close'),
  isMaximized: () => ipcRenderer.invoke('win:is-maximized'),
  onMaximized: (cb) => ipcRenderer.on('window:maximized', (_e, val) => cb(val)),
  browserDetectStart: () => ipcRenderer.send('browser:detect-start'),
  onBrowserTitles: (cb) => ipcRenderer.on('browser:titles', (_e, list) => cb(list)),
  openExternal: (url) => ipcRenderer.invoke('external:open', String(url)),
  focus: () => ipcRenderer.invoke('win:focus'),
  pickFolder: () => ipcRenderer.invoke('fs:pick-folder'),
  listFolder: (dir) => ipcRenderer.invoke('fs:list-files', String(dir)),
  renameFile: (dir, from, to) => ipcRenderer.invoke('fs:rename-file', String(dir), String(from), String(to)),
  copyText: (txt) => ipcRenderer.invoke('clipboard:set-text', String(txt)),
  savePng: (dataUrl, name) => ipcRenderer.invoke('fs:save-png', String(dataUrl), String(name)),
  watchOrganizer: (p) => ipcRenderer.invoke('organizer:watch', p),
  onOrganizerNew: (cb) => ipcRenderer.on('organizer:new', (_e, names) => cb(names)),
  saveState: (data) => ipcRenderer.invoke('state:save', String(data)),
  loadState: () => ipcRenderer.invoke('state:load'),
  stateInfo: () => ipcRenderer.invoke('state:info'),
  stateWipe: () => ipcRenderer.invoke('state:wipe'),
  discordConnect: (p) => ipcRenderer.invoke('discord:connect', p),
  setPresence: (p) => ipcRenderer.invoke('discord:set', p),
  clearPresence: () => ipcRenderer.invoke('discord:stop'),
  onDiscordStatus: (cb) => ipcRenderer.on('discord:status', (_e, s) => cb(s)),
  scrobbleNativeStart: () => ipcRenderer.invoke('scrobble:native-start'),
  scrobbleNativeStop: () => ipcRenderer.invoke('scrobble:native-stop'),
  onScrobbleNative: (cb) => ipcRenderer.on('scrobble:native', (_e, evt) => cb(evt)),
  gameGetStats: () => ipcRenderer.invoke('game:get-stats'),
  gameSaveStats: (stats) => ipcRenderer.invoke('game:save-stats', stats),
  gameListTrophies: () => ipcRenderer.invoke('game:list-trophies'),
  gameAddTrophy: (t) => ipcRenderer.invoke('game:add-trophy', t),
  gameAddHistory: (entry) => ipcRenderer.invoke('game:add-history', entry),
  gameHistory: (limit) => ipcRenderer.invoke('game:history', limit)
});